export const FORM_TYPE_SIMPLE = 'SIMPLE';
export const SIMPLE_WITH_TABS = 'SIMPLE_WITH_TABS';

export const FORM_TYPE_SIMPLE_ARRAY_FIELD_FINAL_FORM = 'FORM_TYPE_SIMPLE_ARRAY_FIELD_FINAL_FORM';
export const FORM_TYPE_SIMPLE_FIELD_FINAL_FORM = 'FORM_TYPE_SIMPLE_FIELD_FINAL_FORM';
export const FORM_TYPE_EXTERNAL_VALIDATORS_FINAL_FORM = 'FORM_TYPE_EXTERNAL_VALIDATORS_FINAL_FORM';
export const FORM_TYPE_EXTERNAL_SUBMIT_FINAL_FORM = 'FORM_TYPE_EXTERNAL_SUBMIT_FINAL_FORM';
export const FORM_TYPE_INITIALIZE_FINAL_FORM = 'FORM_TYPE_INITIALIZE_FINAL_FORM';
export const FORM_TYPE_FORM_SECTION_FINAL_FORM = 'FORM_TYPE_FORM_SECTION_FINAL_FORM';
export const FORM_TYPE_SUBMITION_ERRORS_FINAL_FORM = 'FORM_TYPE_SUBMITION_ERRORS_FINAL_FORM';
