export const FORM_TYPE_SIMPLE = 'FORM_TYPE_SIMPLE';
export const FORM_TYPE_CHILDREN = 'FORM_TYPE_CHILDREN';

export const GENERATE_FORM_TYPE_SIMPLE = 'GENERATE_FORM_TYPE_SIMPLE';
export const GENERATE_FORM_TSIMPLE_WITH_TABS = 'GENERATE_FORM_TSIMPLE_WITH_TABS';

export const FORM_SECTION_TYPE_SIMPLE = 'FORM_SECTION_TYPE_SIMPLE';

export const GENERATE_FORM_SECTION = 'GENERATE_FORM_SECTION';

export const FORM_TYPE_SIMPLE_ARRAY_FIELD_FINAL_FORM = 'FORM_TYPE_SIMPLE_ARRAY_FIELD_FINAL_FORM';
export const FORM_TYPE_SIMPLE_FIELD_FINAL_FORM = 'FORM_TYPE_SIMPLE_FIELD_FINAL_FORM';
export const FORM_TYPE_EXTERNAL_VALIDATORS_FINAL_FORM = 'FORM_TYPE_EXTERNAL_VALIDATORS_FINAL_FORM';
export const FORM_TYPE_EXTERNAL_SUBMIT_FINAL_FORM = 'FORM_TYPE_EXTERNAL_SUBMIT_FINAL_FORM';
export const FORM_TYPE_INITIALIZE_FINAL_FORM = 'FORM_TYPE_INITIALIZE_FINAL_FORM';
export const FORM_TYPE_FORM_SECTION_FINAL_FORM = 'FORM_TYPE_FORM_SECTION_FINAL_FORM';
export const FORM_TYPE_SUBMITION_ERRORS_FINAL_FORM = 'FORM_TYPE_SUBMITION_ERRORS_FINAL_FORM';
